<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Final Test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Final_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Final_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Final_files/libs/quarto-html/popper.min.js"></script>
<script src="Final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Test</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
</section>
<section id="task-1" class="level2">
<h2 class="anchored" data-anchor-id="task-1">Task 1</h2>
<section id="link-to-github-github" class="level4">
<h4 class="anchored" data-anchor-id="link-to-github-github">Link to GitHub: <a href="https://github.com/mt5763standrews/shiny-app-puffin/tree/main">GitHub</a></h4>
</section>
<section id="url-of-published-app" class="level4">
<h4 class="anchored" data-anchor-id="url-of-published-app">URL of Published App:</h4>
</section>
<section id="shiny-app-description" class="level4">
<h4 class="anchored" data-anchor-id="shiny-app-description">Shiny App Description</h4>
<p>Our Shiny App uses the GBIF “Occurrences” API to display&nbsp;occurrences&nbsp;of&nbsp;different species.&nbsp;GBIF stands for “Global&nbsp;Biodiversity Information Facility” and&nbsp;includes various large datasets relating to plant and animal&nbsp;records.&nbsp;Specifically, we used their “Occurrences” API, which gives sightings data for various species across the world. Unfortunately, because of the Occurrences API settings, users are only able to download up to 300 records.&nbsp;</p>
<p>To search for occurrence data, users specify the scientific name of the species they are looking for. They can also specify the country code, region, and years that they want to retrieve data for. The app includes an interactive map that plots where exactly each occurrence was recorded.&nbsp;</p>
<p>[screenshot of&nbsp;panel]&nbsp;</p>
<p>The app includes 3 tabs that users can chose from. The first tab&nbsp;shows the interactive map, the second tab gives a data table for occurrences&nbsp;matching the filters, and the third tab gives as summary of the data&nbsp;requested.&nbsp;&nbsp; &nbsp; [screenshot of tabs]&nbsp;</p>
<p>To download the dataset, users need to click&nbsp;blue “load&nbsp;data” after specifying their filters. Once this data has loaded on the map, users can click&nbsp;the green&nbsp;“download filtered data”&nbsp;button.&nbsp;&nbsp;</p>
</section>
</section>
<section id="task-2-jackknife-analysis" class="level2">
<h2 class="anchored" data-anchor-id="task-2-jackknife-analysis">Task 2: Jackknife Analysis</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>This analysis examines the geographic distribution of bird sightings using biodiversity data extracted from puffins shiny app (we should put link here once we publish it). We focus on two common European bird species: the Blue Tit (<em>Cyanistes caeruleus</em>) and the European Robin (<em>Erithacus rubecula</em>). Our objective is to estimate the mean latitude of bird observations and assess the precision of this estimate using the jackknife resampling method.</p>
<div id="367bfcab" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Total observations loaded: 600
Blue Tit observations: 300
European Robin observations: 300</code></pre>
</div>
</div>
</section>
<section id="data-preparation-and-exploration" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation-and-exploration">Data Preparation and Exploration</h3>
<p>We extract the latitude values from our combined dataset and examine the basic statistics.</p>
<div id="3a817dad" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
DESCRIPTIVE STATISTICS
============================================================
Sample size (n): 600
Range: 50.04° to 57.66°
Mean latitude: 52.6974°
Median latitude: 52.2474°
Standard deviation: 1.6044°
============================================================</code></pre>
</div>
</div>
<p>Our dataset combines 600 bird observations from two species (300 Blue Tits and 300 European Robins) collected across the United Kingdom. The latitude values, representing the geographic north-south position of each sighting, serve as our numerical variable of interest. These observations span from southern England to northern Scotland, providing a comprehensive view of where these species are commonly found.</p>
</section>
<section id="visualization-of-distribution" class="level3">
<h3 class="anchored" data-anchor-id="visualization-of-distribution">Visualization of Distribution</h3>
<p>To understand the geographic distribution of our bird observations, we examine both the central tendency (mean) and the spread of latitude values. The visualization below displays the distribution of observations, with the mean latitude clearly marked to show where bird sightings are centered.<br>
</p>
<div id="42828239" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The histogram reveals a relatively symmetric distribution of latitudes centered around 52.70° North—approximately the latitude of central England. The concentration of observations near this mean, combined with the spread extending from 50° to 57° North, indicates that while these bird species are found throughout the UK, sightings are most common in the central regions. The absence of extreme outliers suggests the data is well-behaved and suitable for both jackknife and analytical methods.</p>
</section>
<section id="jackknife-implementation" class="level3">
<h3 class="anchored" data-anchor-id="jackknife-implementation">Jackknife Implementation</h3>
<p>The jackknife method creates <em>n</em> samples from the original data of size <em>n</em>, where each sample has exactly one observation removed. This systematic approach provides an estimate of the variability of our statistic of interest.</p>
<p>The jackknife estimate of the standard error (SE) is calculated as <span class="math display">\[SE = \sqrt{\frac{n-1}{n} \sum_{i=1}^{n}(\theta_i - \bar{x})^2}, \]</span></p>
<p>where:</p>
<ul>
<li><em>n</em> is the sample size</li>
<li><span class="math inline">\(\theta_i\)</span> is the mean of the original sample</li>
<li><span class="math inline">\(\bar{x}\)</span> is the mean of the <em>i</em>-th jackknife sample (with observation <em>i</em> removed)</li>
</ul>
<div id="20a5abb4" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
JACKKNIFE RESULTS
============================================================
Original sample mean: 52.697367°
Mean of jackknife statistics: 52.697367°
Jackknife Standard Error: 0.065499°
Number of jackknife samples: 600
============================================================</code></pre>
</div>
</div>
<p>The jackknife analysis systematically created 600 samples, each excluding a single observation. The resulting standard error of 0.065499° quantifies the precision of our mean estimate. This small value relative to the mean (52.70°) indicates high precision. Our estimate is accurate to within approximately 7 kilometers, which is remarkably precise given we’re analyzing observations across the entire UK.</p>
</section>
<section id="comparison-with-analytical-standard-error" class="level3">
<h3 class="anchored" data-anchor-id="comparison-with-analytical-standard-error">Comparison with Analytical Standard Error</h3>
<p>We now compare the jackknife estimate with the analytical (theoretical) standard error, which for the mean is calculated as <span class="math display">\[SE_{analytical} = \frac{s}{\sqrt{n}},\]</span> where <em>s</em> is the sample standard deviation and <em>n</em> is the sample size.</p>
<p>This comparison serves two purposes:</p>
<ol type="1">
<li>It confirms the accuracy of our jackknife implementation.</li>
<li>It also verifies that our data meets the assumptions underlying the analytical approach.</li>
</ol>
<div id="9e246c24" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
COMPARISON: JACKKNIFE CS ANALYTICAL
============================================================
Sample size (n):              600
Sample standard deviation:    1.604392°

Analytical Standard Error:    0.065499°
Jackknife Standard Error:     0.065499°
============================================================</code></pre>
</div>
</div>
<p>This identical match indicates that:</p>
<ol type="1">
<li>Our data is well-behaved:The absence of extreme outliers and the approximately normal distribution mean the analytical formula is appropriate.</li>
<li>The jackknife successfully captured variability: The resampling procedure correctly estimated the sampling distribution of the mean.</li>
<li>Both methods are reliable: The agreement validates our computational implementation and confirms we can trust either method for inference.</li>
</ol>
<p>Using our standard error, we construct a 95% confidence interval: [52.70° ± 0.13°] or [52.57°, 52.83°]. This narrow interval reflects the high precision of our estimate, enabled by our large sample size of 600 observations.<br>
</p>
<div id="a6d05bfc" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>
95% Confidence Interval: 52.70° ± 0.1284°
Range: [52.57°, 52.83°]</code></pre>
</div>
</div>
</section>
<section id="visualization-of-jk-statistics" class="level3">
<h3 class="anchored" data-anchor-id="visualization-of-jk-statistics">Visualization of JK Statistics</h3>
<p>The distribution of jackknife statistics provides visual confirmation of our numerical results. Each of the 600 points represents a mean calculated from a dataset with one observation removed. The tight clustering demonstrates the stability of our estimate.</p>
<div id="7cdb6198" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The perfect overlap between the original mean (red line) and the mean of jackknife statistics (green line) confirms that the jackknife procedure introduces no systematic bias. The narrow spread of the distribution, spanning less than 0.5° total, visually illustrates why our standard error is so small and why we can be confident in our estimate.</p>
</section>
<section id="what-does-this-mean-summary-for-non-technical-reader" class="level3">
<h3 class="anchored" data-anchor-id="what-does-this-mean-summary-for-non-technical-reader">What does this mean? (Summary for non technical reader)</h3>
<p>If someone asks “where in the UK are Blue Tits and European Robins typically observed?”, we can confidently answer: around 52.70° North, with high precision.</p>
<p>This precision is valuable for conservation planning, understanding how bird distributions might change with climate, and mapping biodiversity across the UK. The very small standard error means that even with birds observed across a 700+ kilometer range, we can determine the average location with great accuracy thanks to our large sample size.</p>
</section>
</section>
<section id="task-3" class="level2">
<h2 class="anchored" data-anchor-id="task-3">Task 3</h2>
<div id="1425056b" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>There is no missing value in decimalLatitude and decimalLongtitude columns </code></pre>
</div>
</div>
<section id="scatter-plot" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot">Scatter plot</h3>
<p>we will create a visualisation comparing the relationship between <code>decimalLatitude</code> a single numerical response/outcome variable and <code>decimalLongitude</code> a single numerical explanatory variable.</p>
<div id="0dfc6840" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="correlation-check" class="level3">
<h3 class="anchored" data-anchor-id="correlation-check">Correlation check</h3>
<p>Before fitting a linear regression model, we perform a correlation test to check for multicollinearity between the predictors: <code>decimalLatitude</code>,<code>decimalLongitude</code>,<code>coordinateUncertaintyInMeters</code></p>
<div id="dcf3248d" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Text(0.5, 1.0, 'Correlation Matrix')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-15-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The correlation matrix show that there is almost no relationship between these 2 explanatory variables <code>decimalLongitude</code> and <code>coordinateUncertaintyInMeters</code> (correlation = 0.015). Therefore, we include both variables into the regression model.</p>
</section>
<section id="the-biological-signal" class="level3">
<h3 class="anchored" data-anchor-id="the-biological-signal">The Biological Signal</h3>
<p>There is a moderate negative correlation (-0.36) between decimalLatitude vs decimalLongitude, which implies if you move East (Longitude increases), the species tends to be found further South (Latitude decreases).</p>
<p>The correlation is extremely weak (-0.089) between <code>decimalLatitude</code> vs <code>coordinateUncertaintyInMeters</code>. This suggests that <code>coordinateUncertaintyInMeters</code> is likely not a useful variable for predicting where the bird lives. We will see more later if we should drop <code>coordinateUncertaintyInMeters</code> variable, but for now we will keep it.</p>
</section>
<section id="linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression-model">Linear regression model</h3>
<p>We are going to test the linear regression model below with <code>decimalLatitude</code> is a response variable and <code>decimalLongitude</code> and <code>coordinateUncertaintyInMeters</code> are explanatory variables:</p>
<p><span class="math display">\[ decimalLatitude = \beta_0 + \beta_1(decimalLongitude) + \beta_2(coordinateUncertaintyInMeters) + \epsilon \]</span></p>
<div id="f22b9872" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:        decimalLatitude   R-squared:                       0.148
Model:                            OLS   Adj. R-squared:                  0.145
Method:                 Least Squares   F-statistic:                     46.02
Date:                Wed, 26 Nov 2025   Prob (F-statistic):           3.75e-19
Time:                        11:46:38   Log-Likelihood:                -958.19
No. Observations:                 532   AIC:                             1922.
Df Residuals:                     529   BIC:                             1935.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=================================================================================================
                                    coef    std err          t      P&gt;|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                        52.0969      0.094    551.417      0.000      51.911      52.282
decimalLongitude                 -0.3717      0.041     -9.130      0.000      -0.452      -0.292
coordinateUncertaintyInMeters -2.295e-05   8.13e-06     -2.823      0.005   -3.89e-05   -6.98e-06
==============================================================================
Omnibus:                       11.635   Durbin-Watson:                   1.861
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               11.893
Skew:                           0.365   Prob(JB):                      0.00262
Kurtosis:                       3.069   Cond. No.                     1.28e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.28e+04. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<p>The results show that the model is statistically significant (p-value = 9.58e-09). However, the model only explains 13.6% of the variation in latitude: * <code>decimalLongitude</code> (Coefficient: -0.3555 ;P-value: 0.000 ): for every 1 degree we move East, the species moves South by ~0.36 degrees. * <code>coordinateUncertaintyInMeters</code> (Coefficient: -1.93e-05; P-value: 0.151): a p-value &gt; 0.05$ implies that precision of the GPS reading does not reliably predict the latitude of the species. Therefore, we should consider to drop this variable.</p>
</section>
<section id="aic-model-selection" class="level3">
<h3 class="anchored" data-anchor-id="aic-model-selection">AIC model selection</h3>
<p>By finally making sure we should drop <code>coordinateUncertaintyInMeters</code> variable, we defined one more linear regression model (<code>model_reduced</code>) with <code>coordinateUncertaintyInMeters</code> dropped:</p>
<p><span class="math display">\[ decimalLatitude = \beta_0 + \beta_1(decimalLongitude) + \epsilon \]</span></p>
<div id="13928c59" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>AIC of the original model: 1922.39
AIC of reduced model: 1928.34</code></pre>
</div>
</div>
<p>We see that the AIC of the reduced model (933.91) is slightly better than the orginal model (933.82). Therefore, we will drop <code>coordinateUncertaintyInMeters</code> as explanatory variables from our linear regression model.</p>
</section>
<section id="boostrapping-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="boostrapping-linear-regression">Boostrapping linear regression</h3>
<p>To ensure our model is not overfitting to specific outliers, we perform a bootstrap analysis. We resample the dataset with replacement 1000 times and recalculate the coefficients.</p>
<div id="3d67184f" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stdout">
<pre><code>                   Lower CI   Upper CI  Observed Coef
Intercept         51.919886  52.161849      52.038780
decimalLongitude  -0.459336  -0.288507      -0.373275</code></pre>
</div>
</div>
<p>With the bootstrap results, we are 95% confident the true slope <code>decimalLongitude</code> of the population lies between -0.48 and -0.24. For every 1 degree we move East, the species’ range shifts South approximately by 0.24 to 0.48 degrees.</p>
</section>
</section>
<section id="task-4" class="level2">
<h2 class="anchored" data-anchor-id="task-4">Task 4</h2>
<section id="introduction-2" class="level3">
<h3 class="anchored" data-anchor-id="introduction-2">Introduction</h3>
<p>In this task we focus on assessing the difference in mean longitude between bluetits and robins using simulation based and parametric methods. We first construct a randomization based null distribution to obtain an approximate p-value for the difference in means. We then use bootstrap resampling to estimate a 95 percent confidence interval and compare this with the interval from the Welch t test. Finally, we interpret these results jointly to evaluate how strong the evidence is for a genuine difference in mean longitude between the two species.</p>
<div id="ac8dd554" class="cell" data-execution_count="19">
<div class="cell-output cell-output-stdout">
<pre><code>Latitude t test (Bluetit vs Robin)
  t = -1.555, p = 0.12051
  mean lat bluetit = 52.5956
  mean lat robin   = 52.7991
</code></pre>
</div>
</div>
<div id="64d30f2e" class="cell" data-execution_count="20">
<div class="cell-output cell-output-stdout">
<pre><code>Longitude t test (Bluetit vs Robin)
  t = 1.795, p = 0.0731
  mean lon bluetit = -1.5151
  mean lon robin   = -1.7441
</code></pre>
</div>
</div>
</section>
<section id="visual-comparison-of-the-two-groups" class="level3">
<h3 class="anchored" data-anchor-id="visual-comparison-of-the-two-groups">Visual comparison of the two groups</h3>
<p>As we have done before, we will explore whether the two bird species differ in their positions. The following plots help us see both the raw data patterns and the behavior of our test statistics under the null hypothesis and under resampling.</p>
<div id="14775b70" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The first plot compares the observed longitudes for bluetits and robins. Each point represents an individual bird, with the two species shown side by side. The two clouds of points overlap strongly, and both species cover a similar range of longitude values. Robins tend to have slightly lower longitude values on average, which suggests that they may be located somewhat further west, but the visual difference between the groups is fairly subtle.</p>
<div id="9acc5083" class="cell" data-execution_count="22">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The second plot summarises the same longitude data for bluetits and robins using aggregated summaries rather than individual points. The central locations of the two species are close, with the robin distribution shifted slightly towards lower longitudes. The spreads and overall shapes of the two groups are similar, and there are no extreme outliers. This supports the impression from the first plot that any difference in mean longitude between the species is fairly small.</p>
</section>
<section id="randomization-test" class="level3">
<h3 class="anchored" data-anchor-id="randomization-test">Randomization test</h3>
<p>Next we will analyse the difference in mean longitude using a randomization test, adapted from the procedure in chapter 25.2 (*24.2) of the course notes. In that chapter the idea is to construct the sampling distribution of a chosen test statistic under the null hypothesis by repeatedly shuffling the group labels. Here we apply exactly the same idea to our own data on bluetits and robins.</p>
<p>We take as our test statistic the difference in sample means <span class="math display">\[ T = \bar{x}_{\text{robin}} - \bar{x}_{\text{bluetit}}, \]</span> where <span class="math inline">\(\bar{x}_{\text{robin}}\)</span> and <span class="math inline">\(\bar{x}_{\text{bluetit}}\)</span> denote the mean longitudes in each group. Under the null hypothesis <strong>H0</strong> that there is no difference in the mean longitude of the two species, the observed longitude values are assumed to come from the same underlying distribution and the labels <code>robin</code> and <code>bluetit</code> are therefore interchangeable.</p>
<p>To approximate the null distribution of <span class="math inline">\(T\)</span>, we repeatedly shuffle the species labels, recompute the difference in means for each permutation, and store the resulting values. The collection of permuted statistics forms an empirical sampling distribution under <strong>H0</strong>. By comparing the observed statistic <span class="math inline">\(T_{\text{obs}}\)</span> to this null distribution, we obtain an approximate two sided randomization p value for testing whether there is a genuine difference in mean longitude between bluetits and robins.</p>
<p>When applying both the slow and fast randomization tests we get the same observed difference in means <span class="math inline">\(T_{\text{obs}} \approx\)</span> -0.229012 degrees (Robin − Blue tit), represented below by a red line.</p>
<section id="slow-version" class="level4">
<h4 class="anchored" data-anchor-id="slow-version">Slow Version</h4>
<div id="c14fafc4" class="cell" data-execution_count="24">
<div class="cell-output cell-output-stdout">
<pre><code>Total time taken slow version: 0.0686652660369873
Randomization p value (two sided): 0.07592407592407592</code></pre>
</div>
</div>
<div id="0c5c2e91" class="cell" data-execution_count="25">
<div class="cell-output cell-output-display" data-execution_count="25">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-26-output-1.png" width="672" height="480" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>For the slow version of the randomization test, we used the code given in chapter 24.2. By repeatedly shuffling the group labels and recomputing the difference in means, we obtained an approximate null distribution under H0: <strong>no difference in mean longitude.</strong> The observed statistic lies in the tail of this distribution, giving a two sided randomization p value of <span class="math inline">\(p_{\text{rand, slow}}\)</span> = 0.0759.</p>
<p>The classical Welch two sample t test (see the longitude t test results above) produced a very similar p value of 0.0731. This shows that the randomization test and the parametric t test lead to the same conclusion: <strong>at the 5 percent level we do not reject H0</strong>, although the evidence against H0 is not negligible. In conclusion, the p values are essentially identical apart from small Monte Carlo noise, so the randomization test and the parametric t test agree.</p>
</section>
<section id="faster-version" class="level4">
<h4 class="anchored" data-anchor-id="faster-version">Faster version</h4>
<p>The fast version uses exactly the same idea as the slow version, but it avoids doing unnecessary work inside the loop.</p>
<p>In the slow version, each time we shuffle the labels we also repeat several expensive steps, such as creating new data structures and recalculating quantities that do not actually change from one permutation to the next. This makes each permutation a bit heavier and therefore slower.</p>
<p>In the fast version, we keep as much as possible fixed outside the loop and reuse it for every permutation. For example, we work directly with NumPy arrays, avoid creating new objects repeatedly, and only update the parts that really depend on the shuffling of the labels. As a result, each permutation is much cheaper to compute. This is why the fast version can run about three times quicker, even though it produces the same kind of randomised statistics and leads to the same conclusion.</p>
<div id="42836b7a" class="cell" data-execution_count="26">
<div class="cell-output cell-output-stdout">
<pre><code>Total time taken fast version: 0.022477388381958008
Randomization p value (two sided): 0.07992007992007992</code></pre>
</div>
</div>
<div id="82bb304d" class="cell" data-execution_count="27">
<div class="cell-output cell-output-display" data-execution_count="27">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-28-output-1.png" width="672" height="480" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As stated before, the fast version uses the same statistic and the same number of permutations but removes unnecessary work inside the loop. The total time for 1000 permutations decreased from <span class="math inline">\(t_{\text{slow}} \approx\)</span> 0.020 seconds to <span class="math inline">\(t_{\text{fast}} \approx\)</span> 0.007 seconds, which is a speed up by a factor of about <span class="math display">\[ \frac{t_{\text{slow}}}{t_{\text{fast}}} \approx \frac{0.020}{0.007} \approx 2.9 \]</span>.</p>
<p>The randomization p value from the fast implementation was <span class="math inline">\(p_{\text{rand, fast}}\)</span> = 0.0799, which is very close to the slow version. The small difference between <span class="math inline">\(p_{\text{rand, slow}}\)</span> = 0.0759 and <span class="math inline">\(p_{\text{rand, fast}}\)</span> = 0.0799 is within the Monte Carlo variability expected from using 1000 permutations. Therefore the slow and fast versions lead to the same practical conclusion, but the fast implementation achieves this result in roughly one third of the time.</p>
</section>
</section>
<section id="bootstrap-estimate-of-difference-of-means" class="level3">
<h3 class="anchored" data-anchor-id="bootstrap-estimate-of-difference-of-means">Bootstrap estimate of difference of means</h3>
<p>To quantify the uncertainty around the difference in mean longitude between robins and bluetits, we use a bootstrap procedure based on 1000 resamples of the data. For each bootstrap sample we compute the T statistic from before.</p>
<p>The resulting bootstrap distribution of <span class="math inline">\(T\)</span> is approximately centred slightly below zero, reflecting that the observed mean longitude for robins is lower than for bluetits.</p>
<p>From the empirical bootstrap distribution we obtain the 2.5th and 97.5th percentiles, which give a 95% bootstrap confidence interval for the difference in mean longitude of <span class="math display">\[ \text{CI}_{\text{bootstrap}} = [-0.47707, 0.00926] \]</span>.</p>
<p>This interval is visualised in the bootstrap plot below, where the histogram of bootstrap replicates shows the sampling variability of <span class="math inline">\(T\)</span>, and two vertical lines indicate the lower and upper confidence limits.</p>
<div id="aa2818b0" class="cell" data-execution_count="28">
<div class="cell-output cell-output-stdout">
<pre><code>Bootstrap 95 percent CI for difference in mean longitude (Robin - Blue tit):
[-0.47707024  0.00926338]</code></pre>
</div>
</div>
<div id="f724a70c" class="cell" data-execution_count="29">
<div class="cell-output cell-output-display" data-execution_count="29">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-30-output-1.png" width="672" height="480" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="statsmodel-estimate-of-difference-of-means" class="level3">
<h3 class="anchored" data-anchor-id="statsmodel-estimate-of-difference-of-means">Statsmodel estimate of difference of means</h3>
<p>We also compute a 95% confidence interval for the same parameter using the analytical Welch t test as implemented in . This method gives <span class="math display">\[ \text{CI}_{\text{t based}} = [-0.47953, 0.02151] \]</span>.</p>
<p>The two intervals are very similar. Both are centred around a small negative value, consistent with the observed difference in means <span class="math inline">\(T_{\text{obs}}\)</span> = -0.22901, and both intervals include zero. The lower bounds are almost identical (-0.48 to two decimal places), while the upper bound from the t based interval extends slightly further into positive values (0.0215 compared to 0.0093 for the bootstrap interval). In other words, the t based interval is only marginally wider on the upper side.</p>
<p>Since both intervals include zero, they lead to the same statistical conclusion: at the 5% significance level we do <strong>not</strong> have strong enough evidence to claim that the true difference in mean longitude between robins and bluetits is non-zero. The close agreement between the bootstrap and t based intervals also suggests that the assumptions underlying the t test are reasonably compatible with the data in this case.</p>
<div id="71b27a4e" class="cell" data-execution_count="30">
<div class="cell-output cell-output-stdout">
<pre><code>Statsmodels 95 percent CI for difference in mean longitude (Robin - Blue tit):
(np.float64(-0.47953037464537124), np.float64(0.02150572797870437))</code></pre>
</div>
</div>
</section>
<section id="explanation-for-non-technical-audience" class="level3">
<h3 class="anchored" data-anchor-id="explanation-for-non-technical-audience">Explanation for non-technical audience</h3>
<p>In plain terms, we are trying to find out whether robins and bluetits tend to live in different places from west to east (longitudinal coordinates). In our data, robins appear on average about 0.23 degrees further west than bluetits. The question is whether this difference is large enough that we can be confident it reflects a real effect, rather than just random variation in where the birds happened to be observed.</p>
<p>To answer this, we use two methods that both produce a range of possible values for the true difference between the two species. One method (the bootstrap) repeatedly reuses the data in a repetitive way to mimic collecting new samples. The other method relies on a standard statistical formula (the t test). Both approaches give almost the same result (looking at the confidence intervals above): * The true difference could be slightly negative (meaning robins may be a bit further west). * Or it could be very close to zero (meaning the species could be equally distributed).</p>
<p>Because zero lies inside both intervals, the data does not provide strong evidence that robins and bluetits genuinely prefer different longitudes.</p>
<p>So, in conclusion, although robins in this dataset seem a little further west on average, the difference is small enough that it could just be random. Based on these observations, we cannot confidently say the two species occupy different west–east regions of the UK.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>